### ISSUE TITLE
Linux kernel version?

### ISSUE THREAD

**Issue by netbrain** [physics-enthusiast/nixos-nvidia-vgpu#21]
Thanks for this. Been working great on my nixos 23.03 version. However when upgrading to unstable it stopped working. 

[    9.037296] failing symbol_get of non-GPLONLY symbol nv_vgpu_kvm_enable.
[    9.037305] failing symbol_get of non-GPLONLY symbol nvidia_vgpu_vfio_get_ops.
[    9.037306] [nvidia-vgpu-vfio] Unable to get symbol for nvidia_vgpu_vfio_get_ops from nvidia.ko 

Im guessing it has something to do with my kernel version. Do you know which ones this works with?

**Comment by physics-enthusiast** [comment]
Known issue, see https://www.phoronix.com/news/Linux-6.6-Illicit-NVIDIA-Change. The changes have been backported as far back as 5.10 from what I know.

**Comment by netbrain** [comment]
Ok. So unrelated to my move to nixos-stable then. Does this mean we can't
get this to work any more and I'd be better off using PCI passthrough
instead of creating vgpu?

**Comment by physics-enthusiast** [comment]
Currently there appears to be 3 options:
1. Wait for Nvidia to release a new version of their driver that does not use GPL-only symbols. From what I can tell, this should happen when they eventually decide to support a version of linux that uses a kernel which includes this change, if not earlier. Most likely, this will be soon after [the next Ubuntu LTS version releases](https://askubuntu.com/questions/1448224/future-lts-upgrade-from-22-10#:~:text=The%20next%20LTS%20will%20be,be%20supported%20for%20nine%20months).
2. Pin the kernel to a [minor revision](https://discourse.nixos.org/t/override-kernel-version/3638/5) from before the change. Currently running 6.1.47, so at least that version works.
3. Switch back to PCIE passthrough

**Comment by netbrain** [comment]
Thanks for the tip
